name: getx_taskmanager
description: A new Flutter project with GetX state management.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.7
  image_picker: ^1.0.7
  email_validator: ^3.0.0
  pin_code_fields: ^8.0.1
  logger: ^2.5.0
  popover: ^0.2.8     # ✅ Dart 3.1.2 compatible version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
